using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Carbon.InternalCallHookGeneration;

public static class InternalCallHookEmitter
{
	public static string BuildSource(InternalCallHookTypeModel model)
	{
		StringBuilder builder = StringBuilderPool.Rent();
		List<string> list = (from item in model.GlobalUsings.Select(NormalizeUsing)
			where !string.IsNullOrWhiteSpace(item)
			select item).Distinct<string>(StringComparer.Ordinal).OrderBy<string, string>((string item) => item, StringComparer.Ordinal).ToList();
		List<string> list2 = (from item in model.NamespaceUsings.Select(NormalizeUsing)
			where !string.IsNullOrWhiteSpace(item)
			select item).Distinct<string>(StringComparer.Ordinal).OrderBy<string, string>((string item) => item, StringComparer.Ordinal).ToList();
		builder.AppendLine("// <auto-generated/>");
		builder.AppendLine("#nullable disable");
		if (list.Count > 0)
		{
			builder.AppendLine();
			foreach (string item in list)
			{
				builder.Append("using ").Append(item).AppendLine(";");
			}
		}
		builder.AppendLine();
		if (!string.IsNullOrWhiteSpace(model.NamespaceName))
		{
			builder.Append("namespace ").Append(model.NamespaceName).AppendLine();
			builder.AppendLine("{");
			foreach (string item2 in list2)
			{
				builder.Append('\t').Append("using ").Append(item2)
					.AppendLine(";");
			}
			if (list2.Count > 0)
			{
				builder.AppendLine();
			}
			AppendClass(builder, model, 1);
			builder.AppendLine("}");
		}
		else
		{
			AppendClass(builder, model, 0);
		}
		return StringBuilderPool.ToStringAndReturn(ref builder);
	}

	private static void AppendClass(StringBuilder builder, InternalCallHookTypeModel model, int indent)
	{
		AppendLine(builder, indent, "partial class " + model.TypeName);
		AppendLine(builder, indent, "{");
		AppendLine(builder, indent + 1, "public override object InternalCallHook(uint hook, object[] args)");
		AppendLine(builder, indent + 1, "{");
		AppendLine(builder, indent + 2, "var length = args?.Length;");
		int num = ((model.Methods.Count != 0) ? model.Methods.Max((InternalCallHookMethodModel method) => method.Parameters.Count) : 0);
		for (int num2 = 0; num2 < num; num2++)
		{
			AppendLine(builder, indent + 2, $"var narg{num2} = length > {num2} ? args[{num2}] : null;");
		}
		AppendLine(builder, indent + 2, "try");
		AppendLine(builder, indent + 2, "{");
		AppendLine(builder, indent + 3, "switch (hook)");
		AppendLine(builder, indent + 3, "{");
		var list = (from method in model.Methods
			group method by new { method.HookId, method.HookName }).OrderBy(group => group.Key.HookName, StringComparer.Ordinal).ToList();
		foreach (var item in list)
		{
			AppendLine(builder, indent + 4, $"// {item.Key.HookName} aka {item.Key.HookId}");
			AppendLine(builder, indent + 4, $"case {item.Key.HookId}:");
			AppendLine(builder, indent + 4, "{");
			List<InternalCallHookMethodModel> list2 = item.OrderByDescending((InternalCallHookMethodModel method) => method.Score).ThenBy<InternalCallHookMethodModel, string>((InternalCallHookMethodModel method) => method.MethodName, StringComparer.Ordinal).ToList();
			for (int num3 = 0; num3 < list2.Count; num3++)
			{
				AppendMethodInvocation(builder, list2[num3], num3, indent + 5);
			}
			AppendLine(builder, indent + 5, "break;");
			AppendLine(builder, indent + 4, "}");
		}
		AppendLine(builder, indent + 3, "}");
		AppendLine(builder, indent + 2, "}");
		AppendLine(builder, indent + 2, "catch (global::System.Exception ex)");
		AppendLine(builder, indent + 2, "{");
		AppendLine(builder, indent + 3, "global::Carbon.Logger.Error(string.Format(\"Failed to call internal hook '{0}' on " + model.BaseKind + " '{1} v{2}' [{3}]\", global::Carbon.Pooling.HookStringPool.GetOrAdd(hook), " + model.VersionOwnerExpression + ".Name, " + model.VersionOwnerExpression + ".Version, hook), ex);");
		AppendLine(builder, indent + 3, "OnException(hook);");
		AppendLine(builder, indent + 2, "}");
		AppendLine(builder, indent + 2, "return null;");
		AppendLine(builder, indent + 1, "}");
		AppendLine(builder, indent, "}");
	}

	private static void AppendMethodInvocation(StringBuilder builder, InternalCallHookMethodModel method, int methodIndex, int indent)
	{
		if (!string.IsNullOrWhiteSpace(method.ConditionalSymbol))
		{
			AppendLine(builder, indent, "#if " + method.ConditionalSymbol);
		}
		List<string> list = new List<string>(method.Parameters.Count);
		List<string> list2 = new List<string>(method.Parameters.Count);
		for (int i = 0; i < method.Parameters.Count; i++)
		{
			InternalCallHookParameterModel internalCallHookParameterModel = method.Parameters[i];
			string text = $"arg{i}_{methodIndex}";
			string text2 = $"narg{i}_{methodIndex}";
			if (internalCallHookParameterModel.IsOut)
			{
				list2.Add("out var " + text);
				continue;
			}
			if (internalCallHookParameterModel.UseInlineDefaultExpression)
			{
				string patternTypeName = GetPatternTypeName(internalCallHookParameterModel.TypeName);
				list2.Add(string.Format("narg{0} is {1} {2} ? {3} : ({4})default", new object[5] { i, patternTypeName, text, text, internalCallHookParameterModel.TypeName }));
				continue;
			}
			AppendLine(builder, indent, $"var {text2} = narg{i} is {internalCallHookParameterModel.TypeName} or null;");
			AppendLine(builder, indent, string.Format("var {0} = {1} ? ({2})(narg{3} ?? ({4})default) : ({5})default;", new object[6] { text, text2, internalCallHookParameterModel.TypeName, i, internalCallHookParameterModel.TypeName, internalCallHookParameterModel.TypeName }));
			if (internalCallHookParameterModel.RequiresGuard)
			{
				list.Add(text2);
			}
			list2.Add(internalCallHookParameterModel.IsRef ? ("ref " + text) : text);
		}
		if (list.Count > 0)
		{
			AppendLine(builder, indent, "if (" + string.Join(" && ", list) + ")");
			AppendLine(builder, indent, "{");
		}
		int indent2 = indent + ((list.Count > 0) ? 1 : 0);
		AppendLine(builder, indent2, (method.ReturnsVoid ? string.Empty : "return ") + method.MethodName + "(" + string.Join(", ", list2) + ");");
		for (int j = 0; j < method.Parameters.Count; j++)
		{
			InternalCallHookParameterModel internalCallHookParameterModel2 = method.Parameters[j];
			if (internalCallHookParameterModel2.IsRef || internalCallHookParameterModel2.IsOut)
			{
				AppendLine(builder, indent2, $"args[{j}] = arg{j}_{methodIndex};");
			}
		}
		if (method.ReturnsVoid)
		{
			AppendLine(builder, indent2, "return null;");
		}
		if (list.Count > 0)
		{
			AppendLine(builder, indent, "}");
		}
		if (!string.IsNullOrWhiteSpace(method.ConditionalSymbol))
		{
			AppendLine(builder, indent, "#endif");
		}
	}

	private static string NormalizeUsing(string value)
	{
		if (string.IsNullOrWhiteSpace(value))
		{
			return string.Empty;
		}
		value = value.Trim().TrimEnd(';');
		if (value.StartsWith("global ", StringComparison.Ordinal))
		{
			value = value.Substring("global ".Length).TrimStart();
		}
		if (value.StartsWith("using ", StringComparison.Ordinal))
		{
			value = value.Substring("using ".Length);
		}
		return value.Trim();
	}

	private static string GetPatternTypeName(string typeName)
	{
		typeName = typeName.Trim();
		if (!typeName.EndsWith("?", StringComparison.Ordinal))
		{
			return typeName;
		}
		return typeName.Substring(0, typeName.Length - 1).TrimEnd();
	}

	private static void AppendLine(StringBuilder builder, int indent, string line)
	{
		for (int i = 0; i < indent; i++)
		{
			builder.Append('\t');
		}
		builder.AppendLine(line);
	}
}
