using System;
using AntiHackJobs;
using BasePlayerJobs;
using CoarseQueryGridJobs;
using CompanionServer.Cameras;
using Facepunch.MarchingCubes;
using Facepunch.NativeMeshSimplification;
using GamePhysicsJobs;
using GenerateErosionJobs;
using HitBoxSystemJobs;
using Instancing;
using OceanSimulationJobs;
using ProjectileJobs;
using RingGeneratorJobs;
using Rust.Water5;
using ServerOcclusionJobs;
using TerrainHeightMapJobs;
using TerrainTexturingJobs;
using TerrainTopologyMapJobs;
using TerrainWaterMapJobs;
using Unity.Jobs;
using UnityEngine;
using UnityEngine.Jobs;
using UtilityJobs;
using WaterLevelJobs;
using WaterSystemJobs;

[DOTSCompilerGenerated]
internal class __JobReflectionRegistrationOutput__1221673671587648887
{
	public static void CreateJobReflectionData()
	{
		try
		{
			IJobExtensions.EarlyJobInit<FishShoal.FishCollisionGatherJob>();
			IJobExtensions.EarlyJobInit<FishShoal.FishCollisionProcessJob>();
			IJobParallelForExtensions.EarlyJobInit<FishShoal.FishUpdateJob>();
			IJobExtensions.EarlyJobInit<FishShoal.KillFish>();
			IJobParallelForTransformExtensions.EarlyJobInit<QueryVisJobs.ConstructCommandsJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<QueryVisJobs.CheckWaterLevelVisibilityJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformLineRenderer.LineRendererUpdateJob>();
			IJobParallelForExtensions.EarlyJobInit<Hopper.FillRaycastJob>();
			IJobExtensions.EarlyJobInit<GenerateSpawnPoints>();
			IJobExtensions.EarlyJobInit<PostCullingJob>();
			IJobExtensions.EarlyJobInit<DistanceField.GenerateJob>();
			IJobParallelForExtensions.EarlyJobInit<DistanceField.SobelGradientsJob>();
			IJobExtensions.EarlyJobInit<DistanceField.FixBoundaryGradientsJob>();
			IJobParallelForExtensions.EarlyJobInit<DistanceField.BlurHorizontalJob>();
			IJobParallelForExtensions.EarlyJobInit<DistanceField.BlurVerticalJob>();
			IJobExtensions.EarlyJobInit<DistanceField.GaussianBlurJob>();
			IJobExtensions.EarlyJobInit<FlipBoolJob>();
			IJobExtensions.EarlyJobInit<GenerateAscSeqListJob>();
			IJobExtensions.EarlyJobInit<InvertIndexListJob>();
			IJobExtensions.EarlyJobInit<AddVectorJob>();
			IJobExtensions.EarlyJobInit<CheckAnyBoolInGroupJob>();
			IJobExtensions.EarlyJobInit<CheckAnyEnvironmentTypeInGroupJob>();
			IJobExtensions.EarlyJobInit<ScatterToAndJob>();
			IJobExtensions.EarlyJobInit<DiffVec3Indirect>();
			IJobParallelForExtensions.EarlyJobInit<UtilityJobs.BakePhysicsMeshesJob>();
			IJobExtensions.EarlyJobInit<UtilityJobs.BakePhysicsMeshJob>();
			IJobExtensions.EarlyJobInit<RaycastSamplePositionsJob>();
			IJobExtensions.EarlyJobInit<RaycastBufferSetupJob>();
			IJobParallelForExtensions.EarlyJobInit<RaycastRaySetupJob>();
			IJobParallelForExtensions.EarlyJobInit<RaycastRayProcessingJob>();
			IJobExtensions.EarlyJobInit<RaycastOutputCompressJob>();
			IJobExtensions.EarlyJobInit<RaycastColliderProcessingJob>();
			IJobExtensions.EarlyJobInit<GatherPlayersWithTicksJob>();
			IJobExtensions.EarlyJobInit<BuildLayerMasksJob>();
			IJobExtensions.EarlyJobInit<GatherHitIndicesJob>();
			IJobExtensions.EarlyJobInit<BuildBatchLookupMapJob>();
			IJobExtensions.EarlyJobInit<GatherNoClipBatchesJob>();
			IJobExtensions.EarlyJobInit<FindValidIndicesJob>();
			IJobExtensions.EarlyJobInit<InsideTerrainHeightsChecksJob>();
			IJobExtensions.EarlyJobInit<ScatterInvertedBool>();
			IJobForExtensions.EarlyJobInit<GenerateInsideMeshCommandsJob>();
			IJobForExtensions.EarlyJobInit<CheckInsideMeshHitsJob>();
			IJobForExtensions.EarlyJobInit<FilterInsideMeshHitsJob>();
			IJobForExtensions.EarlyJobInit<ProgressSpeedingStatesJob>();
			IJobForExtensions.EarlyJobInit<TransformStartEndTicksJob>();
			IJobForExtensions.EarlyJobInit<CalculateRDCsJob>();
			IJobForExtensions.EarlyJobInit<CalcDistAndBudgetJob>();
			IJobExtensions.EarlyJobInit<AdjustDistBasedOnNormalsJob>();
			IJobForExtensions.EarlyJobInit<TestAreSpeedingJob>();
			IJobExtensions.EarlyJobInit<GatherFlyingBatchesJob>();
			IJobExtensions.EarlyJobInit<BuildFlyingBatchLookupMapJob>();
			IJobExtensions.EarlyJobInit<GatherHitColliderIndicesJob>();
			IJobExtensions.EarlyJobInit<GatherValidWaterIndicesJob>();
			IJobExtensions.EarlyJobInit<CacheInAirStateJob>();
			IJobExtensions.EarlyJobInit<GatherWasInAirStatesJob>();
			IJobExtensions.EarlyJobInit<ProcessFlyhackPauseTimeJob>();
			IJobExtensions.EarlyJobInit<DetermineInAirJob>();
			IJobExtensions.EarlyJobInit<TestAreFlyingJob>();
			IJobForExtensions.EarlyJobInit<CalcSpeedHackSpeedJob>();
			IJobExtensions.EarlyJobInit<PreCullingJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<WaterSystemJobs.FillFalseJobDefer>();
			IJobParallelForDeferExtensions.EarlyJobInit<WaterSystemJobs.AdjustByTopologyJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<OceanSimulationJobs.SmallDisplacementPlaneTraceJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<OceanSimulationJobs.OceanTraceJob>();
			IJobForExtensions.EarlyJobInit<GenerateErosionJobs.PaintSplatJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.PopulateDeltaHeightJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.CopyBackFloatHeightToShortHeightJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.EvaporationJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<GenerateErosionJobs.PrepareMapJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.TransportSedimentJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.CalcMinHeightMapJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.ErosionAndDepositionJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.TileCalculateAngleMap>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.AdjustWaterHeightByFluxJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.CalculateOutputFluxJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.RefillOceanJob>();
			IJobParallelForExtensions.EarlyJobInit<GenerateErosionJobs.WaterIncrementationJob>();
			IJobExtensions.EarlyJobInit<GetCoarseDistsToShoreJobIndirect>();
			IJobExtensions.EarlyJobInit<TerrainTexturingJobs.GenSamplePoints>();
			IJobParallelForExtensions.EarlyJobInit<TerrainTexturingJobs.GenShoreVecBitMapJob>();
			IJobParallelForExtensions.EarlyJobInit<TerrainTexturingJobs.GenTopologyRadiiJob>();
			IJobParallelForExtensions.EarlyJobInit<TerrainTexturingJobs.ProcessTopologyJob>();
			IJobParallelForExtensions.EarlyJobInit<TerrainTexturingJobs.FillAsOceanTopologyJob>();
			IJobParallelForExtensions.EarlyJobInit<TerrainTexturingJobs.PopulateTextureDataJob>();
			IJobExtensions.EarlyJobInit<GetHeightByPosJob>();
			IJobExtensions.EarlyJobInit<GetHeightByUVJob>();
			IJobExtensions.EarlyJobInit<GetHeightByUVJobIndirect>();
			IJobExtensions.EarlyJobInit<GetHeightByIndexJob>();
			IJobExtensions.EarlyJobInit<GetTopologyByPosJob>();
			IJobExtensions.EarlyJobInit<GetTopologyByUVJob>();
			IJobExtensions.EarlyJobInit<TerrainTopologyMapJobs.GetTopologyRadiusJob>();
			IJobParallelForExtensions.EarlyJobInit<TerrainTopologyMapJobs.GetTopologyRadiusJobIndirect>();
			IJobParallelForExtensions.EarlyJobInit<TerrainTopologyMapJobs.GetTopologyRadiusNormalizedJobIndirect>();
			IJobExtensions.EarlyJobInit<GetTopologyByIndexJob>();
			IJobExtensions.EarlyJobInit<GetTopologyByUVJobIndirect>();
			IJobExtensions.EarlyJobInit<GetHeightsByUVJobIndirect>();
			IJobParallelForExtensions.EarlyJobInit<GetHeightsJob>();
			IJobExtensions.EarlyJobInit<GetHeightsJobIndirect>();
			IJobExtensions.EarlyJobInit<GetNormalsJobIndirect>();
			IJobExtensions.EarlyJobInit<GetNormalsJobIndirectDeferred>();
			IJobExtensions.EarlyJobInit<CheckPosRadJob>();
			IJobExtensions.EarlyJobInit<CheckPosRadBatchJob>();
			IJobExtensions.EarlyJobInit<CheckPosRadBatchJobIndirect>();
			IJobExtensions.EarlyJobInit<CheckBoundsJob>();
			IJobExtensions.EarlyJobInit<CheckBoundsJobIndirect>();
			IJobExtensions.EarlyJobInit<CheckRayJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<SliceMeshJob>();
			IJobExtensions.EarlyJobInit<ComputeBoundsJob>();
			IJobParallelForExtensions.EarlyJobInit<SilhouetteSweepJob>();
			IJobExtensions.EarlyJobInit<CalculatePathBetweenGridsJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<CalculatePathsBetweenGridsJob>();
			IJobForExtensions.EarlyJobInit<CalculateSubGridSamplePointsJob>();
			IJobExtensions.EarlyJobInit<GatherMaxWaterLevelsJob>();
			IJobExtensions.EarlyJobInit<ToUVJobIndirect>();
			IJobExtensions.EarlyJobInit<FilterPositionsJobIndirect>();
			IJobExtensions.EarlyJobInit<GatherWavesIndicesJobIndirect>();
			IJobExtensions.EarlyJobInit<ApplyMaxHeightsJobIndirect>();
			IJobExtensions.EarlyJobInit<SelectMaxWaterLevelJobIndirect>();
			IJobExtensions.EarlyJobInit<CalcCenterJobIndirect>();
			IJobExtensions.EarlyJobInit<InitialValidateInfoJobIndirect>();
			IJobExtensions.EarlyJobInit<InitialValidateSimpleInfoJobIndirect>();
			IJobExtensions.EarlyJobInit<GatherValidInfosJobIndirect>();
			IJobExtensions.EarlyJobInit<GatherInvalidInfosJobIndirect>();
			IJobExtensions.EarlyJobInit<UpdateWaterHeightsJobIndirect>();
			IJobExtensions.EarlyJobInit<UpdateWaterHeightsWithVolumesJobIndirect>();
			IJobExtensions.EarlyJobInit<SetupHeadQueryJobIndirect>();
			IJobExtensions.EarlyJobInit<ApplyHeadQueryResultsJobIndirect>();
			IJobExtensions.EarlyJobInit<ResolveWaterInfosJobIndirect>();
			IJobExtensions.EarlyJobInit<ResolveIgnoreWaterInfosJob>();
			IJobExtensions.EarlyJobInit<ResolveWaterInfosSimpleJobIndirect>();
			IJobForExtensions.EarlyJobInit<CalcPlayerSpeedJob>();
			IJobExtensions.EarlyJobInit<BasePlayerJobs.UpdateWaterCache>();
			IJobExtensions.EarlyJobInit<BasePlayerJobs.GatherPosToValidateJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<RecacheTransforms>();
			IJobExtensions.EarlyJobInit<CalcWaterFactorsJobIndirect>();
			IJobExtensions.EarlyJobInit<GetWaterFactorsParamsJobIndirect>();
			IJobForExtensions.EarlyJobInit<HitBoxSystemJobs.TraceAllJob>();
			IJobExtensions.EarlyJobInit<CalcMidpoingJob>();
			IJobExtensions.EarlyJobInit<CheckHitsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapBoxCommandsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapBoxCommandsFromOBBsJob>();
			IJobExtensions.EarlyJobInit<GatherPosFromOBBsJob>();
			IJobExtensions.EarlyJobInit<ValidateOverlapBoxCommandsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapCapsuleCommandsJob>();
			IJobExtensions.EarlyJobInit<ValidateOverlapCapsuleCommandsJob>();
			IJobExtensions.EarlyJobInit<FindSphereCmdsInCapsuleCmdsJob>();
			IJobExtensions.EarlyJobInit<GenerateSphereCmdsFromCapsuleCmdsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapSphereCommandsJob>();
			IJobExtensions.EarlyJobInit<ValidateOverlapSphereCommandsJob>();
			IJobExtensions.EarlyJobInit<RemoveLayerMaskJob>();
			IJobExtensions.EarlyJobInit<ScatterColliderHitsJob>();
			IJobExtensions.EarlyJobInit<GamePhysicsJobs.PreProcessWaterSpheresJob>();
			IJobExtensions.EarlyJobInit<GamePhysicsJobs.PreProcessWaterRaysJob>();
			IJobExtensions.EarlyJobInit<GamePhysicsJobs.PostProcessWaterRaysJob>();
			IJobExtensions.EarlyJobInit<GamePhysicsJobs.AppendRaycastHitsJob>();
			IJobExtensions.EarlyJobInit<SelectNearestHitsJob>();
			IJobExtensions.EarlyJobInit<SelectNearestNHitsJob>();
			IJobExtensions.EarlyJobInit<FilterRaycastHitsJob>();
			IJobExtensions.EarlyJobInit<RemoveInvalidRaycastHitsJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<ProjectileJobs.ReadPositionDataTransformJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<ProjectileJobs.BatchUpdateVelocityEndJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<ProjectileJobs.GenerateRaysJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<ProjectileJobs.GenerateRaysMidstepJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<ProjectileJobs.PosRotReadJob>();
			IJobExtensions.EarlyJobInit<Facepunch.NativeMeshSimplification.CopyBackJob>();
			IJobExtensions.EarlyJobInit<Facepunch.NativeMeshSimplification.PopulateArraysJob>();
			IJobExtensions.EarlyJobInit<Facepunch.NativeMeshSimplification.SimplifyMeshJob>();
			IJobExtensions.EarlyJobInit<FindMaxYLayerJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<Facepunch.MarchingCubes.DownsampleJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<Facepunch.MarchingCubes.MarchFloatGenerateTrianglesJob>();
			IJobExtensions.EarlyJobInit<Facepunch.MarchingCubes.ProcessTrianglesJob>();
			IJobExtensions.EarlyJobInit<Facepunch.MarchingCubes.WriteMeshDataJob>();
			IJobExtensions.EarlyJobInit<Facepunch.MarchingCubes.SDFChunkJobs.CleanupIslandsJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<Facepunch.MarchingCubes.SDFChunkJobs.AccumulateCensorBoundsJob>();
			IJobParallelForExtensions.EarlyJobInit<Facepunch.MarchingCubes.SDFChunkJobs.ApplyCensorBoundsJob>();
			IJobExtensions.EarlyJobInit<Facepunch.MarchingCubes.SDFChunkJobs.ClearBoundariesJob>();
			IJobExtensions.EarlyJobInit<Facepunch.MarchingCubes.SDFChunkJobs.CalculateDistanceFieldJob>();
			IJobExtensions.EarlyJobInit<Rust.Water5.GetHeightBatchedJob>();
			IJobParallelForExtensions.EarlyJobInit<Rust.Water5.GetHeightBatchedJob>();
			IJobExtensions.EarlyJobInit<Rust.Water5.GetHeightsJobIndirect>();
			IJobExtensions.EarlyJobInit<FillJob<int>>();
			IJobExtensions.EarlyJobInit<FillJobUnsafe<BasePlayer.EACTickState>>();
			IJobExtensions.EarlyJobInit<CopyIndirect<Vector3>>();
			IJobExtensions.EarlyJobInit<GatherJob<OverlapCapsuleCommand>>();
			IJobExtensions.EarlyJobInit<ScatterToJob<bool>>();
			IJobExtensions.EarlyJobInit<FillJob<bool>>();
			IJobExtensions.EarlyJobInit<FillJob<float>>();
			IJobForExtensions.EarlyJobInit<SortHitsJob<RaycastHitComparer>>();
			IJobExtensions.EarlyJobInit<FillJob<Vector3>>();
			IJobExtensions.EarlyJobInit<FillJob<WaterLevel.WaterInfo>>();
			IJobExtensions.EarlyJobInit<FillJobIndirect<float>>();
			IJobExtensions.EarlyJobInit<FillJobIndirect<int>>();
			IJobExtensions.EarlyJobInit<GatherJob<Vector3>>();
			IJobExtensions.EarlyJobInit<GatherJob<float>>();
			IJobExtensions.EarlyJobInit<GenerateErosionJobs.CopyArrayJob<float>>();
			IJobExtensions.EarlyJobInit<GatherJob<int>>();
			IJobExtensions.EarlyJobInit<FillJob<RDC>>();
			IJobExtensions.EarlyJobInit<ScatterValueToJobDeferred<Vector3>>();
			IJobExtensions.EarlyJobInit<ClearListJob<Shape>>();
			IJobExtensions.EarlyJobInit<FillJob<Vector4>>();
		}
		catch (Exception ex)
		{
			EarlyInitHelpers.JobReflectionDataCreationFailed(ex);
		}
	}

	[RuntimeInitializeOnLoadMethod(/*Could not decode attribute arguments.*/)]
	public static void EarlyInit()
	{
		CreateJobReflectionData();
	}
}
