using System;
using AntiHackJobs;
using BasePlayerJobs;
using CoarseQueryGridJobs;
using CompanionServer.Cameras;
using Facepunch.MarchingCubes;
using Facepunch.NativeMeshSimplification;
using GamePhysicsJobs;
using GenerateErosionJobs;
using HitBoxSystemJobs;
using Instancing;
using OceanSimulationJobs;
using ProjectileJobs;
using RingGeneratorJobs;
using Rust.Ai.Gen2;
using Rust.Water5;
using ServerOcclusionJobs;
using TerrainHeightMapJobs;
using TerrainTexturingJobs;
using TerrainTopologyMapJobs;
using TerrainWaterMapJobs;
using Unity.Jobs;
using UnityEngine;
using UnityEngine.Jobs;
using UtilityJobs;
using WaterLevelJobs;
using WaterSystemJobs;

[DOTSCompilerGenerated]
internal class __JobReflectionRegistrationOutput__1221673671587648887
{
	public static void CreateJobReflectionData()
	{
		try
		{
			IJobExtensions.EarlyJobInit<CrabGrouping.CrabGroundGatherJob>();
			IJobExtensions.EarlyJobInit<CrabGrouping.CrabGroundProcessJob>();
			IJobExtensions.EarlyJobInit<CrabGrouping.CrabObstacleProcessJob>();
			IJobParallelForExtensions.EarlyJobInit<CrabGrouping.CrabUpdateJob>();
			IJobExtensions.EarlyJobInit<CrabGrouping.KillCrab>();
			IJobExtensions.EarlyJobInit<JellyfishGrouping.JellyfishWaterProcessJob>();
			IJobParallelForExtensions.EarlyJobInit<JellyfishGrouping.JellyfishUpdateJob>();
			IJobExtensions.EarlyJobInit<JellyfishGrouping.KillJellyfish>();
			IJobExtensions.EarlyJobInit<FishShoal.FishCollisionGatherJob>();
			IJobExtensions.EarlyJobInit<FishShoal.FishCollisionProcessJob>();
			IJobParallelForExtensions.EarlyJobInit<FishShoal.FishUpdateJob>();
			IJobExtensions.EarlyJobInit<FishShoal.KillFish>();
			IJobParallelForTransformExtensions.EarlyJobInit<QueryVisJobs.ConstructCommandsJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<QueryVisJobs.CheckWaterLevelVisibilityJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<TransformLineRenderer.LineRendererUpdateJob>();
			IJobParallelForExtensions.EarlyJobInit<Hopper.FillRaycastJob>();
			IJobExtensions.EarlyJobInit<GenerateSpawnPoints>();
			IJobExtensions.EarlyJobInit<PostCullingJob>();
			IJobExtensions.EarlyJobInit<DistanceField.GenerateJob>();
			IJobParallelForExtensions.EarlyJobInit<DistanceField.SobelGradientsJob>();
			IJobExtensions.EarlyJobInit<DistanceField.FixBoundaryGradientsJob>();
			IJobParallelForExtensions.EarlyJobInit<DistanceField.BlurHorizontalJob>();
			IJobParallelForExtensions.EarlyJobInit<DistanceField.BlurVerticalJob>();
			IJobExtensions.EarlyJobInit<DistanceField.GaussianBlurJob>();
			IJobExtensions.EarlyJobInit<FlipBoolJob>();
			IJobExtensions.EarlyJobInit<GenerateAscSeqListJob>();
			IJobExtensions.EarlyJobInit<InvertIndexListJob>();
			IJobExtensions.EarlyJobInit<AddVectorJob>();
			IJobExtensions.EarlyJobInit<CheckAnyBoolInGroupJob>();
			IJobExtensions.EarlyJobInit<CheckAnyEnvironmentTypeInGroupJob>();
			IJobExtensions.EarlyJobInit<ScatterToAndJob>();
			IJobExtensions.EarlyJobInit<DiffVec3Indirect>();
			IJobParallelForExtensions.EarlyJobInit<BakePhysicsMeshesJob>();
			IJobExtensions.EarlyJobInit<BakePhysicsMeshJob>();
			IJobExtensions.EarlyJobInit<RaycastSamplePositionsJob>();
			IJobExtensions.EarlyJobInit<RaycastBufferSetupJob>();
			IJobParallelForExtensions.EarlyJobInit<RaycastRaySetupJob>();
			IJobParallelForExtensions.EarlyJobInit<RaycastRayProcessingJob>();
			IJobExtensions.EarlyJobInit<RaycastOutputCompressJob>();
			IJobExtensions.EarlyJobInit<RaycastColliderProcessingJob>();
			IJobExtensions.EarlyJobInit<GatherPlayersWithTicksJob>();
			IJobExtensions.EarlyJobInit<BuildLayerMasksJob>();
			IJobExtensions.EarlyJobInit<GatherHitIndicesJob>();
			IJobExtensions.EarlyJobInit<BuildBatchLookupMapJob>();
			IJobExtensions.EarlyJobInit<GatherNoClipBatchesJob>();
			IJobExtensions.EarlyJobInit<FindValidIndicesJob>();
			IJobExtensions.EarlyJobInit<InsideTerrainHeightsChecksJob>();
			IJobExtensions.EarlyJobInit<ScatterInvertedBool>();
			IJobForExtensions.EarlyJobInit<GenerateInsideMeshCommandsJob>();
			IJobForExtensions.EarlyJobInit<CheckInsideMeshHitsJob>();
			IJobForExtensions.EarlyJobInit<FilterInsideMeshHitsJob>();
			IJobForExtensions.EarlyJobInit<ProgressSpeedingStatesJob>();
			IJobForExtensions.EarlyJobInit<TransformStartEndTicksJob>();
			IJobForExtensions.EarlyJobInit<CalculateRDCsJob>();
			IJobForExtensions.EarlyJobInit<CalcDistAndBudgetJob>();
			IJobExtensions.EarlyJobInit<AdjustDistBasedOnNormalsJob>();
			IJobForExtensions.EarlyJobInit<TestAreSpeedingJob>();
			IJobExtensions.EarlyJobInit<GatherFlyingBatchesJob>();
			IJobExtensions.EarlyJobInit<BuildFlyingBatchLookupMapJob>();
			IJobExtensions.EarlyJobInit<GatherHitColliderIndicesJob>();
			IJobExtensions.EarlyJobInit<GatherValidWaterIndicesJob>();
			IJobExtensions.EarlyJobInit<CacheInAirStateJob>();
			IJobExtensions.EarlyJobInit<GatherWasInAirStatesJob>();
			IJobExtensions.EarlyJobInit<ProcessFlyhackPauseTimeJob>();
			IJobExtensions.EarlyJobInit<DetermineInAirJob>();
			IJobExtensions.EarlyJobInit<TestAreFlyingJob>();
			IJobForExtensions.EarlyJobInit<CalcSpeedHackSpeedJob>();
			IJobExtensions.EarlyJobInit<PreCullingJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<FillFalseJobDefer>();
			IJobParallelForDeferExtensions.EarlyJobInit<AdjustByTopologyJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<SmallDisplacementPlaneTraceJob>();
			IJobParallelForDeferExtensions.EarlyJobInit<OceanTraceJob>();
			IJobForExtensions.EarlyJobInit<PaintSplatJob>();
			IJobParallelForExtensions.EarlyJobInit<PopulateDeltaHeightJob>();
			IJobParallelForExtensions.EarlyJobInit<CopyBackFloatHeightToShortHeightJob>();
			IJobParallelForExtensions.EarlyJobInit<EvaporationJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<PrepareMapJob>();
			IJobParallelForExtensions.EarlyJobInit<TransportSedimentJob>();
			IJobParallelForExtensions.EarlyJobInit<CalcMinHeightMapJob>();
			IJobParallelForExtensions.EarlyJobInit<ErosionAndDepositionJob>();
			IJobParallelForExtensions.EarlyJobInit<TileCalculateAngleMap>();
			IJobParallelForExtensions.EarlyJobInit<AdjustWaterHeightByFluxJob>();
			IJobParallelForExtensions.EarlyJobInit<CalculateOutputFluxJob>();
			IJobParallelForExtensions.EarlyJobInit<RefillOceanJob>();
			IJobParallelForExtensions.EarlyJobInit<WaterIncrementationJob>();
			IJobExtensions.EarlyJobInit<GetCoarseDistsToShoreJobIndirect>();
			IJobExtensions.EarlyJobInit<GenSamplePoints>();
			IJobParallelForExtensions.EarlyJobInit<GenShoreVecBitMapJob>();
			IJobExtensions.EarlyJobInit<HasLandJob>();
			IJobParallelForExtensions.EarlyJobInit<GenTopologyRadiiJob>();
			IJobParallelForExtensions.EarlyJobInit<ProcessTopologyJob>();
			IJobParallelForExtensions.EarlyJobInit<FillAsOceanTopologyJob>();
			IJobParallelForExtensions.EarlyJobInit<PopulateTextureDataJob>();
			IJobExtensions.EarlyJobInit<GetHeightByPosJob>();
			IJobExtensions.EarlyJobInit<GetHeightByUVJob>();
			IJobExtensions.EarlyJobInit<GetHeightByUVJobIndirect>();
			IJobExtensions.EarlyJobInit<GetHeightByIndexJob>();
			IJobExtensions.EarlyJobInit<GetTopologyByPosJob>();
			IJobExtensions.EarlyJobInit<GetTopologyByUVJob>();
			IJobExtensions.EarlyJobInit<GetTopologyRadiusJob>();
			IJobParallelForExtensions.EarlyJobInit<GetTopologyRadiusJobIndirect>();
			IJobParallelForExtensions.EarlyJobInit<GetTopologyRadiusNormalizedJobIndirect>();
			IJobExtensions.EarlyJobInit<GetTopologyByIndexJob>();
			IJobExtensions.EarlyJobInit<GetTopologyByUVJobIndirect>();
			IJobExtensions.EarlyJobInit<GetHeightsByUVJobIndirect>();
			IJobParallelForExtensions.EarlyJobInit<GetHeightsJob>();
			IJobExtensions.EarlyJobInit<TerrainHeightMapJobs.GetHeightsJobIndirect>();
			IJobExtensions.EarlyJobInit<GetNormalsJobIndirect>();
			IJobExtensions.EarlyJobInit<GetNormalsJobIndirectDeferred>();
			IJobExtensions.EarlyJobInit<CheckPosRadJob>();
			IJobExtensions.EarlyJobInit<CheckPosRadBatchJob>();
			IJobExtensions.EarlyJobInit<CheckPosRadBatchJobIndirect>();
			IJobExtensions.EarlyJobInit<CheckBoundsJob>();
			IJobExtensions.EarlyJobInit<CheckBoundsJobIndirect>();
			IJobExtensions.EarlyJobInit<CheckRayJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<SliceMeshJob>();
			IJobExtensions.EarlyJobInit<ComputeBoundsJob>();
			IJobParallelForExtensions.EarlyJobInit<SilhouetteSweepJob>();
			IJobExtensions.EarlyJobInit<CalculatePathBetweenGridsJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<CalculatePathsBetweenGridsJob>();
			IJobForExtensions.EarlyJobInit<CalculateSubGridSamplePointsJob>();
			IJobExtensions.EarlyJobInit<GatherMaxWaterLevelsJob>();
			IJobExtensions.EarlyJobInit<ToUVJobIndirect>();
			IJobExtensions.EarlyJobInit<FilterPositionsJobIndirect>();
			IJobExtensions.EarlyJobInit<GatherWavesIndicesJobIndirect>();
			IJobExtensions.EarlyJobInit<ApplyMaxHeightsJobIndirect>();
			IJobExtensions.EarlyJobInit<SelectMaxWaterLevelJobIndirect>();
			IJobExtensions.EarlyJobInit<CalcCenterJobIndirect>();
			IJobExtensions.EarlyJobInit<InitialValidateInfoJobIndirect>();
			IJobExtensions.EarlyJobInit<InitialValidateSimpleInfoJobIndirect>();
			IJobExtensions.EarlyJobInit<GatherValidInfosJobIndirect>();
			IJobExtensions.EarlyJobInit<GatherInvalidInfosJobIndirect>();
			IJobExtensions.EarlyJobInit<UpdateWaterHeightsJobIndirect>();
			IJobExtensions.EarlyJobInit<UpdateWaterHeightsWithVolumesJobIndirect>();
			IJobExtensions.EarlyJobInit<SetupHeadQueryJobIndirect>();
			IJobExtensions.EarlyJobInit<ApplyHeadQueryResultsJobIndirect>();
			IJobExtensions.EarlyJobInit<ResolveWaterInfosJobIndirect>();
			IJobExtensions.EarlyJobInit<ResolveIgnoreWaterInfosJob>();
			IJobExtensions.EarlyJobInit<ResolveWaterInfosSimpleJobIndirect>();
			IJobForExtensions.EarlyJobInit<CalcPlayerSpeedJob>();
			IJobExtensions.EarlyJobInit<UpdateWaterCache>();
			IJobExtensions.EarlyJobInit<GatherPosToValidateJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<RecacheTransforms>();
			IJobExtensions.EarlyJobInit<CalcWaterFactorsJobIndirect>();
			IJobExtensions.EarlyJobInit<GetWaterFactorsParamsJobIndirect>();
			IJobForExtensions.EarlyJobInit<TraceAllJob>();
			IJobExtensions.EarlyJobInit<CalcMidpoingJob>();
			IJobExtensions.EarlyJobInit<CheckHitsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapBoxCommandsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapBoxCommandsFromOBBsJob>();
			IJobExtensions.EarlyJobInit<GatherPosFromOBBsJob>();
			IJobExtensions.EarlyJobInit<ValidateOverlapBoxCommandsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapCapsuleCommandsJob>();
			IJobExtensions.EarlyJobInit<ValidateOverlapCapsuleCommandsJob>();
			IJobExtensions.EarlyJobInit<FindSphereCmdsInCapsuleCmdsJob>();
			IJobExtensions.EarlyJobInit<GenerateSphereCmdsFromCapsuleCmdsJob>();
			IJobExtensions.EarlyJobInit<GenerateOverlapSphereCommandsJob>();
			IJobExtensions.EarlyJobInit<ValidateOverlapSphereCommandsJob>();
			IJobExtensions.EarlyJobInit<RemoveLayerMaskJob>();
			IJobExtensions.EarlyJobInit<ScatterColliderHitsJob>();
			IJobExtensions.EarlyJobInit<PreProcessWaterSpheresJob>();
			IJobExtensions.EarlyJobInit<PreProcessWaterRaysJob>();
			IJobExtensions.EarlyJobInit<PostProcessWaterRaysJob>();
			IJobExtensions.EarlyJobInit<AppendRaycastHitsJob>();
			IJobExtensions.EarlyJobInit<SelectNearestHitsJob>();
			IJobExtensions.EarlyJobInit<SelectNearestNHitsJob>();
			IJobExtensions.EarlyJobInit<FilterRaycastHitsJob>();
			IJobExtensions.EarlyJobInit<RemoveInvalidRaycastHitsJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<ReadPositionDataTransformJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<BatchUpdateVelocityEndJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<GenerateRaysJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<GenerateRaysMidstepJob>();
			IJobParallelForTransformExtensions.EarlyJobInit<PosRotReadJob>();
			IJobExtensions.EarlyJobInit<CopyBackJob>();
			IJobExtensions.EarlyJobInit<PopulateArraysJob>();
			IJobExtensions.EarlyJobInit<SimplifyMeshJob>();
			IJobExtensions.EarlyJobInit<FindMaxYLayerJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<DownsampleJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<MarchFloatGenerateTrianglesJob>();
			IJobExtensions.EarlyJobInit<ProcessTrianglesJob>();
			IJobExtensions.EarlyJobInit<WriteMeshDataJob>();
			IJobExtensions.EarlyJobInit<SDFChunkJobs.CleanupIslandsJob>();
			IJobParallelForBatchExtensions.EarlyJobInit<SDFChunkJobs.AccumulateCensorBoundsJob>();
			IJobParallelForExtensions.EarlyJobInit<SDFChunkJobs.ApplyCensorBoundsJob>();
			IJobExtensions.EarlyJobInit<SDFChunkJobs.ClearBoundariesJob>();
			IJobExtensions.EarlyJobInit<SDFChunkJobs.CalculateDistanceFieldJob>();
			IJobExtensions.EarlyJobInit<GetHeightBatchedJob>();
			IJobParallelForExtensions.EarlyJobInit<GetHeightBatchedJob>();
			IJobExtensions.EarlyJobInit<Rust.Water5.GetHeightsJobIndirect>();
			IJobParallelForTransformExtensions.EarlyJobInit<RustNavMeshAgent.MovementTransformJob>();
			IJobExtensions.EarlyJobInit<FillJob<int>>();
			IJobExtensions.EarlyJobInit<FillJobUnsafe<BasePlayer.EACTickState>>();
			IJobExtensions.EarlyJobInit<CopyIndirect<Vector3>>();
			IJobExtensions.EarlyJobInit<GatherJob<OverlapCapsuleCommand>>();
			IJobExtensions.EarlyJobInit<ScatterToJob<bool>>();
			IJobExtensions.EarlyJobInit<FillJob<bool>>();
			IJobExtensions.EarlyJobInit<FillJob<float>>();
			IJobForExtensions.EarlyJobInit<SortHitsJob<RaycastHitComparer>>();
			IJobExtensions.EarlyJobInit<FillJob<Vector3>>();
			IJobExtensions.EarlyJobInit<FillJob<WaterLevel.WaterInfo>>();
			IJobExtensions.EarlyJobInit<FillJobIndirect<float>>();
			IJobExtensions.EarlyJobInit<FillJobIndirect<int>>();
			IJobExtensions.EarlyJobInit<GatherJob<Vector3>>();
			IJobExtensions.EarlyJobInit<GatherJob<float>>();
			IJobExtensions.EarlyJobInit<FillJob<Vector4>>();
			IJobExtensions.EarlyJobInit<CopyArrayJob<float>>();
			IJobExtensions.EarlyJobInit<GatherJob<int>>();
			IJobExtensions.EarlyJobInit<FillJob<RDC>>();
			IJobExtensions.EarlyJobInit<ScatterValueToJobDeferred<Vector3>>();
			IJobExtensions.EarlyJobInit<ClearListJob<Shape>>();
		}
		catch (Exception ex)
		{
			EarlyInitHelpers.JobReflectionDataCreationFailed(ex);
		}
	}

	[RuntimeInitializeOnLoadMethod(/*Could not decode attribute arguments.*/)]
	public static void EarlyInit()
	{
		CreateJobReflectionData();
	}
}
