using System;
using ConVar;
using Facepunch.Rust;
using Network;
using Oxide.Core;
using UnityEngine;
using UnityEngine.Assertions;

public class ThrownWeapon : AttackEntity
{
	public enum PredictRelease
	{
		HandSlows,
		Delay,
		ViewmodelEvent
	}

	public enum PredictOrigin
	{
		ViewmodelBone,
		ThrowRoot,
		Eyes
	}

	[Header("Throw Prediction")]
	public bool predictThrow = true;

	[Tooltip("What makes the throwable leave the hand and become visible.")]
	[ShowIf("predictThrow", true)]
	public PredictRelease predictRelease;

	[ShowIf("predictRelease", PredictRelease.Delay)]
	[Tooltip("Delay mode: seconds after the throw starts. 0 lets go at once.")]
	[ShowIf("predictThrow", true)]
	public float predictReleaseDelay;

	[ShowIf("predictThrow", true)]
	[ShowIf("predictRelease", PredictRelease.HandSlows)]
	[Range(0.05f, 0.95f)]
	[Tooltip("Hand Slows mode: lets go once the hand has dropped to this share of its fastest speed.")]
	public float predictReleaseSpeed = 0.5f;

	[Tooltip("Viewmodel Event mode: the animation event that lets it go.")]
	[ShowIf("predictThrow", true)]
	[ShowIf("predictRelease", PredictRelease.ViewmodelEvent)]
	public string predictReleaseEvent;

	[Tooltip("Backstop: it leaves the hand this long after the throw whatever the mode decides.")]
	[ShowIf("predictThrow", true)]
	public float predictMaxHoldTime = 0.5f;

	[Tooltip("What the throwable comes off when it appears.")]
	[ShowIf("predictThrow", true)]
	public PredictOrigin predictOrigin;

	[ShowIf("predictOrigin", PredictOrigin.ViewmodelBone)]
	[ShowIf("predictThrow", true)]
	[Tooltip("Viewmodel Bone mode: the viewmodel bone to follow.")]
	public string predictOriginBone = "r_hand";

	[Tooltip("Viewmodel Bone mode: start in the bone's pose and blend to the throw's own over the blend distance.")]
	[ShowIf("predictOrigin", PredictOrigin.ViewmodelBone)]
	[ShowIf("predictThrow", true)]
	public bool predictOriginRotation;

	[Tooltip("Shifts where it appears, along the origin's own axes.")]
	[ShowIf("predictThrow", true)]
	public Vector3 predictOriginOffset;

	[Tooltip("How far it has to travel from where it appeared before it is drawn.")]
	[ShowIf("predictThrow", true)]
	public float predictRevealDistance = 0.3f;

	[Tooltip("Distance over which it moves from where it appeared onto the server's arc.")]
	[ShowIf("predictThrow", true)]
	public float predictBlendDistance = 2.5f;

	[Tooltip("Generated by prepare. A version of the prefab with just meshes, particles and lights")]
	[ShowIf("predictThrow", true)]
	[ReadOnly]
	public GameObjectRef predictedEntity;

	[Header("Throw Weapon")]
	public GameObjectRef prefabToThrow;

	public float maxThrowVelocity = 10f;

	public float tumbleVelocity;

	public Vector3 overrideAngle = Vector3.zero;

	public bool canStick = true;

	public bool canThrowUnderwater = true;

	public bool canThrowFromHelicopter = true;

	public GameObject throwObjectRoot;

	private const float stickRadius = 0.05f;

	private const float stickDistance = 1.5f;

	public override bool OnRpcMessage(BasePlayer player, uint rpc, Message msg)
	{
		using (TimeWarning.New("ThrownWeapon.OnRpcMessage"))
		{
			if (rpc == 1513023343 && (Object)(object)player != (Object)null)
			{
				Assert.IsTrue(player.isServer, "SV_RPC Message is using a clientside player!");
				if (Global.developer > 2)
				{
					Debug.Log((object)("SV_RPCMessage: " + ((object)player)?.ToString() + " - DoDrop"));
				}
				using (TimeWarning.New("DoDrop"))
				{
					using (TimeWarning.New("Conditions"))
					{
						if (!RPC_Server.IsActiveItem.Test(1513023343u, "DoDrop", this, player))
						{
							return true;
						}
					}
					try
					{
						using (TimeWarning.New("Call"))
						{
							RPCMessage msg2 = new RPCMessage
							{
								connection = msg.connection,
								player = player,
								read = msg.read
							};
							DoDrop(msg2);
						}
					}
					catch (Exception ex)
					{
						Debug.LogException(ex);
						player.Kick("RPC Error in DoDrop");
					}
				}
				return true;
			}
			if (rpc == 1974840882 && (Object)(object)player != (Object)null)
			{
				Assert.IsTrue(player.isServer, "SV_RPC Message is using a clientside player!");
				if (Global.developer > 2)
				{
					Debug.Log((object)("SV_RPCMessage: " + ((object)player)?.ToString() + " - DoThrow"));
				}
				using (TimeWarning.New("DoThrow"))
				{
					using (TimeWarning.New("Conditions"))
					{
						if (!RPC_Server.IsActiveItem.Test(1974840882u, "DoThrow", this, player))
						{
							return true;
						}
					}
					try
					{
						using (TimeWarning.New("Call"))
						{
							RPCMessage msg3 = new RPCMessage
							{
								connection = msg.connection,
								player = player,
								read = msg.read
							};
							DoThrow(msg3);
						}
					}
					catch (Exception ex2)
					{
						Debug.LogException(ex2);
						player.Kick("RPC Error in DoThrow");
					}
				}
				return true;
			}
		}
		return base.OnRpcMessage(player, rpc, msg);
	}

	public override Vector3 GetInheritedVelocity(BasePlayer player, Vector3 direction)
	{
		//IL_0001: Unknown result type (might be due to invalid IL or missing references)
		//IL_0002: Unknown result type (might be due to invalid IL or missing references)
		return player.GetInheritedThrowVelocity(direction);
	}

	public Vector3 ComputeThrowVelocity(BasePlayer player, Vector3 eyeDir, float throwScale, Vector3 playerVelocity)
	{
		//IL_0002: Unknown result type (might be due to invalid IL or missing references)
		//IL_0003: Unknown result type (might be due to invalid IL or missing references)
		//IL_0008: Unknown result type (might be due to invalid IL or missing references)
		//IL_000f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0015: Unknown result type (might be due to invalid IL or missing references)
		//IL_001a: Unknown result type (might be due to invalid IL or missing references)
		//IL_001f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0026: Unknown result type (might be due to invalid IL or missing references)
		//IL_002b: Unknown result type (might be due to invalid IL or missing references)
		return GetInheritedVelocity(player, eyeDir) + eyeDir * maxThrowVelocity * throwScale + playerVelocity * 0.5f;
	}

	public void ServerThrow(Vector3 targetPosition)
	{
		//IL_0053: Unknown result type (might be due to invalid IL or missing references)
		//IL_0058: Unknown result type (might be due to invalid IL or missing references)
		//IL_005f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0064: Unknown result type (might be due to invalid IL or missing references)
		//IL_0089: Unknown result type (might be due to invalid IL or missing references)
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0090: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a4: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a5: Unknown result type (might be due to invalid IL or missing references)
		//IL_009d: Unknown result type (might be due to invalid IL or missing references)
		//IL_00aa: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ca: Unknown result type (might be due to invalid IL or missing references)
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00d5: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Unknown result type (might be due to invalid IL or missing references)
		//IL_00df: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e4: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00eb: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ec: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ed: Unknown result type (might be due to invalid IL or missing references)
		//IL_013d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0141: Unknown result type (might be due to invalid IL or missing references)
		//IL_0147: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ff: Unknown result type (might be due to invalid IL or missing references)
		//IL_0105: Unknown result type (might be due to invalid IL or missing references)
		//IL_010a: Unknown result type (might be due to invalid IL or missing references)
		//IL_010f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0114: Unknown result type (might be due to invalid IL or missing references)
		//IL_0119: Unknown result type (might be due to invalid IL or missing references)
		//IL_011e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0120: Unknown result type (might be due to invalid IL or missing references)
		//IL_0121: Unknown result type (might be due to invalid IL or missing references)
		//IL_0122: Unknown result type (might be due to invalid IL or missing references)
		//IL_018d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0198: Unknown result type (might be due to invalid IL or missing references)
		if (isClient || !HasItemAmount() || HasAttackCooldown())
		{
			return;
		}
		BasePlayer ownerPlayer = GetOwnerPlayer();
		if ((Object)(object)ownerPlayer == (Object)null || (!canThrowUnderwater && ownerPlayer.IsHeadUnderwater()) || (!canThrowFromHelicopter && ownerPlayer.IsInAHelicopter()))
		{
			return;
		}
		Vector3 position = ownerPlayer.eyes.position;
		Vector3 val = ownerPlayer.eyes.BodyForward();
		float num = 1f;
		SignalBroadcast(Signal.Throw, string.Empty);
		BaseEntity baseEntity = GameManager.server.CreateEntity(prefabToThrow.resourcePath, position, Quaternion.LookRotation((overrideAngle == Vector3.zero) ? (-val) : overrideAngle));
		if ((Object)(object)baseEntity == (Object)null)
		{
			return;
		}
		baseEntity.SetCreatorEntity(ownerPlayer);
		Vector3 val2 = val + Quaternion.AngleAxis(10f, Vector3.right) * Vector3.up;
		float num2 = GetThrowVelocity(position, targetPosition, val2);
		if (float.IsNaN(num2))
		{
			val2 = val + Quaternion.AngleAxis(20f, Vector3.right) * Vector3.up;
			num2 = GetThrowVelocity(position, targetPosition, val2);
			if (float.IsNaN(num2))
			{
				num2 = 5f;
			}
		}
		baseEntity.SetVelocity(val2 * num2 * num);
		if (tumbleVelocity > 0f)
		{
			baseEntity.SetAngularVelocity(new Vector3(Random.Range(-1f, 1f), Random.Range(-1f, 1f), Random.Range(-1f, 1f)) * tumbleVelocity);
		}
		baseEntity.Spawn();
		StartAttackCooldown(repeatDelay);
		UseItemAmount(1);
		if ((Object)(object)(baseEntity as TimedExplosive) != (Object)null)
		{
			Facepunch.Rust.Analytics.Azure.OnExplosiveLaunched(ownerPlayer, baseEntity);
		}
	}

	public static float GetThrowVelocity(Vector3 throwPos, Vector3 targetPos, Vector3 aimDir)
	{
		//IL_0000: Unknown result type (might be due to invalid IL or missing references)
		//IL_0001: Unknown result type (might be due to invalid IL or missing references)
		//IL_0002: Unknown result type (might be due to invalid IL or missing references)
		//IL_0007: Unknown result type (might be due to invalid IL or missing references)
		//IL_0008: Unknown result type (might be due to invalid IL or missing references)
		//IL_000e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0014: Unknown result type (might be due to invalid IL or missing references)
		//IL_0019: Unknown result type (might be due to invalid IL or missing references)
		//IL_0023: Unknown result type (might be due to invalid IL or missing references)
		//IL_002a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_0036: Unknown result type (might be due to invalid IL or missing references)
		//IL_003b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0045: Unknown result type (might be due to invalid IL or missing references)
		//IL_004d: Unknown result type (might be due to invalid IL or missing references)
		Vector3 val = targetPos - throwPos;
		Vector2 val2 = new Vector2(val.x, val.z);
		float magnitude = val2.magnitude;
		float y = val.y;
		val2 = new Vector2(aimDir.x, aimDir.z);
		float magnitude2 = val2.magnitude;
		float y2 = aimDir.y;
		float y3 = Physics.gravity.y;
		return Mathf.Sqrt(0.5f * y3 * magnitude * magnitude / (magnitude2 * (magnitude2 * y - y2 * magnitude)));
	}

	[RPC_Server]
	[RPC_Server.IsActiveItem]
	private void DoThrow(RPCMessage msg)
	{
		//IL_0006: Unknown result type (might be due to invalid IL or missing references)
		//IL_000b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0012: Unknown result type (might be due to invalid IL or missing references)
		//IL_0017: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0020: Unknown result type (might be due to invalid IL or missing references)
		//IL_0051: Unknown result type (might be due to invalid IL or missing references)
		//IL_006f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0070: Unknown result type (might be due to invalid IL or missing references)
		//IL_007f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0085: Unknown result type (might be due to invalid IL or missing references)
		Vector3 eyePos = msg.read.Vector3();
		Vector3 throwVelocityOverride = msg.read.Vector3();
		Vector3 normalized = throwVelocityOverride.normalized;
		float throwScale = Mathf.Clamp01(msg.read.Float());
		uint num = msg.read.UInt32();
		if (!HasItemAmount() || HasAttackCooldown() || !DoValidationChecks(ref eyePos, normalized, msg.player, throwScale))
		{
			SendThrowResult(msg.player, num, null);
			return;
		}
		Vector3 eyePos2 = eyePos;
		BasePlayer player = msg.player;
		uint throwID = num;
		throwVelocityOverride = default;
		DoThrowImpl(eyePos2, normalized, player, out var thrownEntity, throwScale, throwVelocityOverride, null, throwID);
		Interface.CallHook("OnExplosiveThrown", msg.player, thrownEntity, this);
		if ((Object)(object)thrownEntity == (Object)null)
		{
			SendThrowResult(msg.player, num, null);
		}
		else
		{
			UseItemAmount(1, reduceItemOwnership: false);
		}
	}

	public bool DoValidationChecks(ref Vector3 eyePos, Vector3 eyeDir, BasePlayer owningPlayer, float throwScale)
	{
		//IL_0000: Unknown result type (might be due to invalid IL or missing references)
		//IL_002c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0031: Unknown result type (might be due to invalid IL or missing references)
		//IL_003b: Unknown result type (might be due to invalid IL or missing references)
		if (Vector3Ex.IsNaNOrInfinity(eyeDir))
		{
			return false;
		}
		if (FloatEx.IsNaNOrInfinity(throwScale))
		{
			return false;
		}
		if (owningPlayer.isMounted || owningPlayer.HasParent())
		{
			eyePos = owningPlayer.eyes.position;
		}
		else if (!ValidateEyePos(owningPlayer, eyePos))
		{
			return false;
		}
		if (!canThrowUnderwater && owningPlayer.IsHeadUnderwater())
		{
			return false;
		}
		if (!canThrowFromHelicopter && owningPlayer.IsInAHelicopter())
		{
			return false;
		}
		return true;
	}

	public void DoThrowImpl(Vector3 eyePos, Vector3 eyeDir, BasePlayer owningPlayer, out BaseEntity thrownEntity, float throwScale = 1f, Vector3 throwVelocityOverride = default(Vector3), Item ownerItemOverride = null, uint throwID = 0u)
	{
		//IL_0016: Unknown result type (might be due to invalid IL or missing references)
		//IL_0018: Unknown result type (might be due to invalid IL or missing references)
		//IL_001d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0031: Unknown result type (might be due to invalid IL or missing references)
		//IL_0032: Unknown result type (might be due to invalid IL or missing references)
		//IL_002a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0037: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a6: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a8: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c1: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c5: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ca: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b5: Unknown result type (might be due to invalid IL or missing references)
		//IL_010f: Unknown result type (might be due to invalid IL or missing references)
		//IL_011a: Unknown result type (might be due to invalid IL or missing references)
		thrownEntity = null;
		BaseEntity baseEntity = (thrownEntity = GameManager.server.CreateEntity(prefabToThrow.resourcePath, eyePos, Quaternion.LookRotation((overrideAngle == Vector3.zero) ? (-eyeDir) : overrideAngle)));
		if (!((Object)(object)baseEntity == (Object)null))
		{
			Item item = ownerItemOverride ?? GetOwnerItem();
			if (item != null && item.instanceData != null && item.HasFlag(Item.Flag.IsOn))
			{
				((Component)baseEntity).gameObject.SendMessage("SetFrequency", (object)item.instanceData.dataInt, (SendMessageOptions)1);
			}
			baseEntity.SetCreatorEntity(owningPlayer);
			baseEntity.skinID = skinID;
			if (throwVelocityOverride != Vector3.zero)
			{
				baseEntity.SetVelocity(throwVelocityOverride);
			}
			else
			{
				baseEntity.SetVelocity(ComputeThrowVelocity(owningPlayer, eyeDir, throwScale, owningPlayer.estimatedVelocity));
			}
			if (tumbleVelocity > 0f)
			{
				baseEntity.SetAngularVelocity(new Vector3(Random.Range(-1f, 1f), Random.Range(-1f, 1f), Random.Range(-1f, 1f)) * tumbleVelocity);
			}
			SpawnThrownEntity(baseEntity, owningPlayer, throwID);
			if (baseEntity is TimedExplosive timedExplosive)
			{
				ItemOwnershipShare itemOwnership = item.TakeOwnershipShare();
				timedExplosive.ItemOwnership = itemOwnership;
				timedExplosive.SetCreator(owningPlayer);
			}
			SetUpThrownWeapon(baseEntity, item);
			StartAttackCooldown(repeatDelay);
		}
	}

	[RPC_Server.IsActiveItem]
	[RPC_Server]
	private void DoDrop(RPCMessage msg)
	{
		//IL_0006: Unknown result type (might be due to invalid IL or missing references)
		//IL_000b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0012: Unknown result type (might be due to invalid IL or missing references)
		//IL_0017: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0020: Unknown result type (might be due to invalid IL or missing references)
		//IL_0040: Unknown result type (might be due to invalid IL or missing references)
		//IL_0071: Unknown result type (might be due to invalid IL or missing references)
		//IL_0072: Unknown result type (might be due to invalid IL or missing references)
		//IL_0077: Unknown result type (might be due to invalid IL or missing references)
		//IL_0144: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a5: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a6: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a7: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c6: Unknown result type (might be due to invalid IL or missing references)
		//IL_00cb: Unknown result type (might be due to invalid IL or missing references)
		//IL_00cf: Unknown result type (might be due to invalid IL or missing references)
		//IL_00d4: Unknown result type (might be due to invalid IL or missing references)
		//IL_00d6: Unknown result type (might be due to invalid IL or missing references)
		//IL_013b: Unknown result type (might be due to invalid IL or missing references)
		//IL_011d: Unknown result type (might be due to invalid IL or missing references)
		//IL_011f: Unknown result type (might be due to invalid IL or missing references)
		Vector3 eyePos = msg.read.Vector3();
		Vector3 val = msg.read.Vector3();
		Vector3 normalized = val.normalized;
		uint throwID = msg.read.UInt32();
		if (!HasItemAmount() || HasAttackCooldown() || !DoValidationChecks(ref eyePos, normalized, msg.player, 1f))
		{
			SendThrowResult(msg.player, throwID, null);
			return;
		}
		BaseEntity baseEntity = GameManager.server.CreateEntity(prefabToThrow.resourcePath, eyePos, Quaternion.LookRotation(Vector3.up));
		if ((Object)(object)baseEntity == (Object)null)
		{
			SendThrowResult(msg.player, throwID, null);
			return;
		}
		RaycastHit hit = default;
		if (canStick && Physics.SphereCast(new Ray(eyePos, normalized), 0.05f, ref hit, 1.5f, 1237003025))
		{
			Vector3 point = hit.point;
			Vector3 normal = hit.normal;
			BaseEntity entity = RaycastHitEx.GetEntity(hit);
			Collider collider = hit.collider;
			if (Object.op_Implicit((Object)(object)entity) && entity is StabilityEntity && baseEntity is TimedExplosive)
			{
				entity = entity.ToServer<BaseEntity>();
				TimedExplosive timedExplosive = baseEntity as TimedExplosive;
				timedExplosive.onlyDamageParent = true;
				timedExplosive.DoStick(point, normal, entity, collider);
				Facepunch.Rust.Analytics.Azure.OnExplosiveLaunched(msg.player, timedExplosive);
			}
			else
			{
				baseEntity.SetVelocity(normalized);
			}
		}
		else
		{
			baseEntity.SetVelocity(normalized);
		}
		baseEntity.creatorEntity = msg.player;
		baseEntity.skinID = skinID;
		SpawnThrownEntity(baseEntity, msg.player, throwID);
		SetUpThrownWeapon(baseEntity, GetOwnerItem());
		StartAttackCooldown(repeatDelay);
		Interface.CallHook("OnExplosiveDropped", msg.player, baseEntity, this);
		UseItemAmount(1);
	}

	protected virtual void SetUpThrownWeapon(BaseEntity ent, Item ownerItem)
	{
	}

	private static void SpawnThrownEntity(BaseEntity entity, BasePlayer player, uint throwID)
	{
		if (throwID != 0)
		{
			if (entity.net == null)
			{
				entity.net = Net.sv.CreateNetworkable();
			}
			if (entity is TimedExplosive timedExplosive)
			{
				timedExplosive.SetPredictedThrower(player);
			}
			SendThrowResult(player, throwID, entity);
		}
		entity.Spawn();
	}

	private static void SendThrowResult(BasePlayer player, uint throwID, BaseEntity entity)
	{
		//IL_001f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0025: Unknown result type (might be due to invalid IL or missing references)
		//IL_0034: Unknown result type (might be due to invalid IL or missing references)
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_005e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0051: Unknown result type (might be due to invalid IL or missing references)
		//IL_0063: Unknown result type (might be due to invalid IL or missing references)
		//IL_0075: Unknown result type (might be due to invalid IL or missing references)
		//IL_006d: Unknown result type (might be due to invalid IL or missing references)
		//IL_007a: Unknown result type (might be due to invalid IL or missing references)
		//IL_008c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0084: Unknown result type (might be due to invalid IL or missing references)
		//IL_0091: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a1: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a3: Unknown result type (might be due to invalid IL or missing references)
		if (throwID != 0)
		{
			NetworkableId arg = (((Object)(object)entity != (Object)null && !entity.IsDestroyed && entity.net != null) ? entity.net.ID : default(NetworkableId));
			Rigidbody val = (arg.IsValid ? ((Component)entity).GetComponent<Rigidbody>() : null);
			Vector3 arg2 = (arg.IsValid ? ((Component)entity).transform.position : Vector3.zero);
			Vector3 arg3 = (((Object)(object)val != (Object)null) ? val.linearVelocity : Vector3.zero);
			Vector3 arg4 = (((Object)(object)val != (Object)null) ? val.angularVelocity : Vector3.zero);
			player.ClientRPC(RpcTarget.Player("Client_ThrowResult", player), throwID, arg, arg2, arg3, arg4);
		}
	}

	public ThrownWeapon()
	{
		//IL_004a: Unknown result type (might be due to invalid IL or missing references)
		//IL_004f: Unknown result type (might be due to invalid IL or missing references)
	}
}
