<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Carbon.Hooks.Oxide</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Carbon.SDK" />
    <Reference Include="0Harmony" />
    <Reference Include="Rust.Clans" />
    <Reference Include="Rust.Clans.Local" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="Rust.Localization" />
    <Reference Include="UnityEngine.CoreModule" />
    <Reference Include="System.Core">
      <HintPath>../../../../../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.10/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Carbon.Common" />
    <Reference Include="Rust.Data" />
    <Reference Include="Rust.Global" />
  </ItemGroup>
</Project>