<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Oxide.Core</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Oxide.Common">
      <HintPath>../../../../../../../tmp/oxide-extract/RustDedicated_Data/Managed/Oxide.Common.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.10/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Oxide.References">
      <HintPath>../../../../../../../tmp/oxide-extract/RustDedicated_Data/Managed/Oxide.References.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony" />
    <Reference Include="System.Data">
      <HintPath>../../../../../../../tmp/oxide-extract/RustDedicated_Data/Managed/System.Data.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>